# Generated by Django 4.2.9 on 2024-01-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report_28',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.CharField(default='Driver', max_length=25)),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_email', models.EmailField(blank=True, max_length=254)),
                ('car', models.CharField(default='28', max_length=50)),
                ('location_at_time_of_fault', models.TextField(max_length=60)),
                ('time_of_fault', models.TimeField(blank=True, null=True)),
                ('date_of_fault', models.TextField()),
                ('defect_keyword', models.TextField(choices=[('Brake Issue', 'Brake Issue'), ('main engine', 'main engine'), ('gen engine', 'gen engine'), ('EDC fault', 'EDC fault'), ('TDC fault', 'TDC fault'), ('bad oil level', 'bad oil level'), ('low HYDRO oil', 'low HYDRO oil'), ('low coolant', 'low coolant'), ('door', 'door'), ('wiper', 'wiper'), ('radio', 'radio'), ('wheel flats', 'wheel flats'), ('HVAC', 'HVAC'), ('Heating', 'Heating'), ('caws', 'caws'), ('headlamps', 'headlamps'), ('mmi', 'mmi'), ('Cab Seals', 'Cab Seals'), ('Window', 'Window'), ('Internal Lights', 'Internal Lights'), ('External Lights', 'External Lights'), ('Saloon Issues', 'Saloon Issues'), ('Fuel Issues', 'Fuel Issues')], default='', help_text='(By selecting a keyword, this will later help to search and identify problematic trends on a unit)')),
                ('defect_details', models.TextField(default='')),
                ('ref_number', models.IntegerField(blank=True, null=True)),
                ('status_changed', models.BooleanField(default=False)),
                ('report_read', models.BooleanField(default=False)),
                ('work_order_created', models.BooleanField(default=False)),
                ('driver_emailed', models.BooleanField(default=True)),
                ('work_order_closed', models.BooleanField(default=False)),
                ('work_order_number', models.IntegerField(blank=True, null=True)),
                ('Depot_feedback', models.TextField(default='Copy SAP longtext here', max_length=300)),
            ],
            options={
                'ordering': ['date_of_fault'],
            },
        ),
    ]
